name: Générer le fichier ICS des congés WBE

on:
  schedule:
    - cron: '0 6 * * 1'  # Chaque lundi à 6h00 UTC (7h heure belge)
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run ICS generation script
      run: python generate_ics.py

    - name: Archive generated ICS
      uses: actions/upload-artifact@v3
      with:
        name: conges_scolaires_wbe_ics
        path: conges_scolaires_wbe_futurs.ics
